version: 2
jobs:
  deploy_stage:
    docker:
      - image: cimg/node:16.13.2
    environment:
      CI: false
    resource_class: large
    steps:
      - checkout
      - run: yarn upgrade "@web3-onboard/coinbase@next"
      - run: yarn upgrade "@web3-onboard/fortmatic@next"
      - run: yarn upgrade "@web3-onboard/gnosis@next"
      - run: yarn upgrade "@web3-onboard/injected-wallets@next"
      - run: yarn upgrade "@web3-onboard/keepkey@next"
      - run: yarn upgrade "@web3-onboard/keystone@next"
      - run: yarn upgrade "@web3-onboard/ledger@next"
      - run: yarn upgrade "@web3-onboard/magic@next"
      - run: yarn upgrade "@web3-onboard/portis@next"
      - run: yarn upgrade "@web3-onboard/react@next"
      - run: yarn upgrade "@web3-onboard/torus@next"
      - run: yarn upgrade "@web3-onboard/trezor@next"
      - run: yarn upgrade "@web3-onboard/web3auth@next"
      - run: yarn install --network-concurrency 1
      - run: yarn build-staging
      - run: touch .env
      - run: echo "REACT_APP_GOOGLE_ANALYTICS_ID=$REACT_APP_GOOGLE_ANALYTICS_ID" > .env
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/remove.sh reactdemo-staging"
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo-staging/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo-staging"
  
  deploy_prod:
    docker:
      - image: cimg/node:16.13.2
    environment:
      CI: false
    resource_class: large
    steps:
      - checkout
      - run: yarn cache clean
      - run: yarn install --network-concurrency 1
      - run: yarn build
      - run: touch .env
      - run: echo "REACT_APP_GOOGLE_ANALYTICS_ID=$REACT_APP_GOOGLE_ANALYTICS_ID" > .env
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/remove.sh reactdemo"
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo"
workflows:
  version: 2
  test_build:
    jobs:
      - deploy_stage:
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          filters:
            branches:
              only:
                - master
