version: 2
jobs:
  deploy_stage:
    docker:
      - image: cimg/node:14.17.3
    resource_class: large
    steps:
      - checkout
      - run: rm yarn.lock && yarn install --network-concurrency 1
      - run: yarn build-staging
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/remove.sh reactdemo-staging"
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo-staging/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo-staging"
  
  deploy_prod:
    docker:
      - image: cimg/node:14.17.3
    resource_class: large
    steps:
      - checkout
      - run: yarn cache clean && yarn install --network-concurrency 1
      - run: yarn build
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/remove.sh reactdemo"
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo"
workflows:
  version: 2
  test_build:
    jobs:
      - deploy_stage:
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          filters:
            branches:
              only:
                - master
