name: PR Status Checks

on:
  # Allows it to be manually triggered, used primarily for debugging
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master

jobs:
  checks:
    name: 'Checks'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nodejs and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Check that it builds
        run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
          CI: false
